Fix Pytest INTERNALERROR when running on with doctests.
Causes:

```
INTERNALERROR>   File "../lib/python3.7/site-packages/kubetest/plugin.py", line 269, in pytest_runtest_makereport
INTERNALERROR>     if 'kube' in item.fixturenames and call.when == 'call':
INTERNALERROR> AttributeError: 'DoctestItem' object has no attribute 'fixturenames'
```

when run on testsuite with doctests.